alias r="ranger"
alias h="htop"

alias cfa="$GUI_EDITOR ~/.bash_aliases"
alias cfb="$GUI_EDITOR ~/.bashrc"
alias cfi="$GUI_EDITOR ~/.config/i3/config"
alias cfp="$GUI_EDITOR ~/.profile"
alias cfr="$GUI_EDITOR ~/.config/ranger/rc.conf"
alias cfri="$GUI_EDITOR ~/.config/ranger/rifle.conf"
alias cfv="$GUI_EDITOR ~/.vimrc"
alias cfx="$GUI_EDITOR ~/.Xresources"
alias cfz="$GUI_EDITOR ~/.zshrc"

alias vcfa="$EDITOR ~/.bash_aliases"
alias vcfb="$EDITOR ~/.bashrc"
alias vcfi="$EDITOR ~/.config/i3/config"
alias vcfp="$EDITOR ~/.profile"
alias vcfr="$EDITOR ~/.config/ranger/rc.conf"
alias vcfri="$EDITOR ~/.config/ranger/rifle.conf"
alias vcfv="$EDITOR ~/.vimrc"
alias vcfx="$EDITOR ~/.Xresources"
alias vcfz="$EDITOR ~/.zshrc"

alias ga="cd ~/Audiobooks"
alias gb="cd ~/Ebooks"
alias gd="cd ~/Documents"
alias gD="cd ~/Downloads"
alias gm="cd ~/Movies"
alias gmb="cd ~/Movies/Bengali"
alias gme="cd ~/Movies/English"
alias gmh="cd ~/Movies/Hindi"
alias gmi="cd ~/Movies/International"
alias gt="cd ~/TV"

alias ma="mv $1 ~/Audiobooks"
alias mb="mv $1 ~/Ebooks"
alias md="mv $1 ~/Documents"
alias mD="mv $1 ~/Downloads"
alias mm="mv $1 ~/Movies"
alias mmb="mv $1 ~/Movies/Bengali"
alias mme="mv $1 ~/Movies/English"
alias mmh="mv $1 ~/Movies/Hindi"
alias mmi="mv $1 ~/Movies/International"
alias mt="mv $1 ~/TV"

alias cozy='flatpak run com.github.geigi.cozy'
alias config='/usr/bin/git --git-dir=/home/illuminatus/.dotfiles/ --work-tree=/home/illuminatus'
