# options
source-file ~/.config/tmux/tmux-options.conf

# keybinds
source-file ~/.config/tmux/tmux-keybinds.conf

# statusbar
source-file ~/.config/tmux/tmux-statusbar.conf

# colors
source-file ~/.config/tmux/tmux-colors.conf

# plugins and plugin options
source-file ~/.config/tmux/tmux-plugins.conf

# Initialize tmux plugin manager
run -b '~/.tmux/plugins/tpm/tpm'
