# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'abhinav/tmux-fastcopy'
set -g @plugin 'laktak/extrakto'

# Plugin options
set -g @prefix_highlight_show_copy_mode "on"
set -g @continuum-restore "on"
set -g @continuum-save-internal "15"
set -g @resurrect-capture-pane-contents "on"
set -g @sessionx-bind "O"
set -g @extrakto_fzf_tool "fzf"
set -g @fastcopy-action "tmux load-buffer -; tmux paste-buffer"
