#!/bin/bash

function make_link () {
    mode=$1
    mount_name=$2
    directory_name=$3
    if [ $mode == "usb" ]; then
            link_path="$HOME/HDD"
    else
            link_path="$HOME"
    fi
    if [ -L "$link_path/$directory_name" ]; then
            rm "$link_path/$directory_name"
    fi
    path=$(find "/mnt/$mount_name" -maxdepth 1 -type d -name "$directory_name*")
    ln -s "$path" "$link_path/$directory_name"
}

# Symlinks for internal storage
make_link int sda1 Audiobooks
make_link int sda1 Documentaries
make_link int sda1 Ebooks
make_link int sda1 Memes
make_link int sda1 Movies
make_link int sda1 TV

# Symlinks for external usb storage
make_link usb usb-Sg2TB Audiobooks
make_link usb usb-Sg2TB Ebooks
make_link usb usb-Sg2TB Documentaries
make_link usb usb-Sg2TB Movies
make_link usb usb-Sg2TB TV
make_link usb usb-Sg2TB Tutorials
