#!/bin/bash

# Feed script a url
# If an image, it will view in feh,
# If a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

ext="${1##*.}"
mpvFiles="mkv mp4 avi mov wmv flv gif"
fehFiles="bpm jpg jpeg png"
wgetFiles="mp3 flac opus mp3?source=feed pdf"

if echo $fehFiles | grep -w $ext > $HOME/Pictures/feh/; then
    nohup feh "$1" > $HOME/Pictures/feh/ &
elif echo $mpvFiles | grep -w $ext > $HOME/Downloads/; then
    nohup mpv --loop --quiet "$1" > $HOME/Downloads/ &
elif echo $wgetFiles | grep -w $ext > $HOME/Pictures/feh/; then
    nohup wget "$1" > $HOME/Downloads/ &
elif echo $1 | grep youtube > $HOME/Pictures/feh/; then
    nohup mpv "$1" > $HOME/Downloads/ &
elif echo $1 | grep youtu.be > $HOME/Pictures/feh/; then
    nohup mpv "$1" > $HOME/Downloads/ &
elif echo $1 | grep vimeo > $HOME/Pictures/feh/; then
    nohup mpv "$1" > $HOME/Downloads/ &
else
    nohup $BROWSER "$1" > $HOME/Downloads &
fi
